### ISSUE TITLE
Bot don't start

### ISSUE THREAD

**Issue by babyrig** [verata-veritatis/bybit-market-maker#7]
Hello sir,

I am trying to run this bot for the first time on ETHUSD but after install and configured shows me:

 python run.py
2021-01-10 11:29:17 - pybit - INFO - Initializing HTTP session.
2021-01-10 11:29:17 - pybit - INFO - Initializing Authenticated WebSocket.
2021-01-10 11:29:19 - pybit - INFO - Authorization successful.
2021-01-10 11:29:19 - pybit - INFO - Subscription to ['instrument_info.100ms.ETHUSD', 'position', 'order'] successful.
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    market_maker.Application()
  File "/root/build/bybit/1/bybit-market-maker/market_maker/market_maker.py", line 242, in __init__
    Algorithm().run()
  File "/root/build/bybit/1/bybit-market-maker/market_maker/market_maker.py", line 189, in run
    median, interval, qty = self.submit_initial()
  File "/root/build/bybit/1/bybit-market-maker/market_maker/market_maker.py", line 133, in submit_initial
    balance = self.req.get_wallet_balance() * last_price * MARGIN
  File "/root/build/bybit/1/bybit-market-maker/market_maker/market_maker.py", line 88, in get_wallet_balance
    r = self.session.get_wallet_balance('BTC')
TypeError: get_wallet_balance() takes 1 positional argument but 2 were given

It's something on my side ? Can you give me a direction ? thanks

**Comment by verata-veritatis** [comment]
`pybit` has changed drastically and this market maker no longer works as it currently stands, but I've been working on an improved version for a little bit. Potentially this week or next.

**Comment by verata-veritatis** [comment]
I will post in here again when the market maker has been updated
